chore: bump version to v0.7.4
nervosnetwork/molecule pull request #66
Opened 2023-02-20 01:41 UTC by eval-exec

We have merged "custom Union ID" feature (#65 ) into master, then bump version from `0.7.3` to `v0.7.4`. @yangby-cryptape @quake

2023-02-20 01:45 UTC, eval-exec commented
The CI action failed on "make clippy", investigating the cause.

2023-02-20 01:45 UTC, yangby-cryptape requested changes
Some versions of dependencies in `Cargo.toml` should be updated.

For examples:

- https://github.com/nervosnetwork/molecule/blob/c75422b7d1c62a95ccad0c1894b77efab55ed528/tools/codegen/Cargo.toml#L19

- https://github.com/nervosnetwork/molecule/blob/c75422b7d1c62a95ccad0c1894b77efab55ed528/tools/compiler/Cargo.toml#L33

2023-02-20 01:53 UTC, yangby-cryptape approved these changes

2023-02-20 01:59 UTC, quake submitted a review, later dismissed

2023-02-21 06:55 UTC, quake approved these changes

2023-02-21 07:16 UTC, yangby-cryptape approved these changes

2023-02-21 07:17 UTC, merged